### ISSUE TITLE
(Question) What CI CAM did you use?

### ISSUE THREAD

**Issue by yuppi3** [therealcouchpotato/nonaxe#3]
In nonaxe.ini you mentioned about some popups in Samsung TV, so I assume that you had it running on some CAM.
Could you share details about CI CAM and baudrate?

I already tried with Technicrypt CX but no luck. I had some communication at baudrate 12800 but card wasn't initializing properly.

**Comment by therealcouchpotato** [comment]
It was a long time ago so I don't remember the specifics, sorry. I tried two different OEMs and the one that wasn't SMiT had firmware issues where it would stop working after it was left in stand-by for too long but this was unrelated to the emulator (encountered by many when used in Samsung TVs) and it worked fine otherwise. Both ran at different baud rates from what I remember.
If you measure the clock the CAM is outputting then dividing it by 372 should give you the proper baud rate (I think).

eg.:
3.5712MHz = 3571200 Hz / 372 = 9600
4Mhz = 10 752
5Mhz = 13 441
etc..

dwDataRate column on this page should give you a few others to try if you don't want to do that:
http://pcsclite.alioth.debian.org/ccid/iManufacturer.html

**Comment by yuppi3** [comment]
What could be tolerance from original baudrate? I mean how accurate value I must find?

**Comment by therealcouchpotato** [comment]
From memory +/-50bps should work and +/-100 should work with corruption.

How are you getting the non-standard bauds to work (are you using a baud table modified CP2xxx?) and what OS are you using?

**Comment by yuppi3** [comment]
Yes, I'm using CP2102 and modifying table under Windows (in nonaxe.ini baudrate is 9600). Nonaxe is running under Ubuntu 16.04 LTS. I read card in Phoenix 6Mhz, so interface is working ok.

In range of baudrate 12350-13650 log is identical like this: http://pastebin.com/3XwSeEXb
So I assumed baudrate is ok, and just Technicrypt is sending some unsupported command "DDC2000003660100". 
That's why I was asking about another CI CAM in first place.

**Comment by therealcouchpotato** [comment]
Yup, all seems fine with your method and interface and you're right about the TechniCrypt CAM sending an unsupported command (or parameter to be exact). The init commands were consistent for all my test devices (2 cams and 2 stbs) and they didn't include the last serial read with a 3 byte ID parameter.
What I've always seen:
C2(read serial) command with parameter length 2, content 6600
What your cam is sending
C2(read serial) command with parameter length 3, content 660100

I've put in a check to exit in case it ever receives a C2 command with a parameter that isn't 2 bytes because I never came across that situation and wouldn't know what to do.

Things you could try:
- Build a MITM interface and log the communication between the cam and the real card then implement the proper response for that serial ID in uConaxCard.pas\ConaxCard.handleReadSerial (also change the type of the ID variable to a Cardinal and change the last parameter of the Move command to Length(packet), etc.. )
- Remove or comment out the two Halt(0) statements in the function (this will return an empty response for the unknown ID)
- Remove the case statement so that the response for 6600 returns all the time (this should work if the 660100 request needs an identical(or similar) response to the 6600 one).
  No telling what will happen if you try the latter two though. You do so at your own risk :-)

**Comment by therealcouchpotato** [comment]
Hope you find the the solution. Please let me know if you do either with a pull request or just the details so that I can add the changes to the source. I'll close the issue in a week if there's no other contact. Thanks

**Comment by yuppi3** [comment]
I found partially solution but I'm not sure it's solved or bypassed.

I sent these requests to real cards using smartcard reader. Answers were always identical. But if it should return a serial number then i messed something up.

```
< DDC2000003
> C2
< 660100
> 9806

< DDC2000002
> C2
< 6600
> 9806 
```

So I started with assumption that answers are identical.
I don't have programming skills. I just changed packet length from "2" to "3" and "$6600" to "$6601".
It looks like card is initializing properly.

I said partially becasue it sometimes freeze after "Adding ECM Response:" on "ACK (34 bytes available)", but it seems inrelated. I will experiment later, maybe more accurate baudrate helps.

**Comment by therealcouchpotato** [comment]
Oh right, you could just use a reader. Totally slipped my mind.
98 is ACK, 06 is length of answer. There's actually a "GET ANSWER" command that you have to issue after a request to read the actual answer.
Try sending DD CA 00 00 06 after you get the 9806, that should read the 6 byte answer. If you can confirm that the two commands return the same answer I'll modify the code to support both.

Baud could be an issue. I'd try the standard ones on the site linked above. I think they usually run the cards at "standard" clock rates so either round numbers like 4/5/6Mhz or if it's an unstandard value it'll be because it lines up with one of the standard baud rates (eg. 3.5712->9600)
My guess would be that yours runs at 5Mhz / 13441bps based on what you said.

You could also try disabling some of the debug output options to see if that helps. I remember there were some kind of timeout issues with all of them enabled (although it could've been with the Java emu, not sure now.)

**Comment by yuppi3** [comment]
Yes, both commands return the same answer (including serial).

**Comment by therealcouchpotato** [comment]
Cool, thanks.
Could you check if this modification works?

[uConaxCard.pas.zip](https://github.com/therealcouchpotato/nonaxe/files/474452/uConaxCard.pas.zip)

**Comment by yuppi3** [comment]
```
[ConaxCard] 17-9-16 00:03:16 TRACE: handleCommand
[ConaxCard] 17-9-16 00:03:16 Received:
DDC2000003660100
[ConaxCard] 17-9-16 00:03:16 TRACE: handleReadSerial
[ConaxCard] 17-9-16 00:03:16 handleReadSerial received unknown parameter66010000
. Exiting preemptively. 
```

**Comment by therealcouchpotato** [comment]
Ah, right. My bad. Checked in the fixed version just now. Should work fine. If you can confirm I'll close the issue as fixed. Thanks

**Comment by yuppi3** [comment]
Yes, it works.

**Comment by therealcouchpotato** [comment]
Thanks for confirming :+1:
Closing Issue.
